site_name: Media Framing
site_url: https://media-framing.com/
theme:
 name: "material"
 plugins:
  - search
  - mkdocstrings:
      module: modules  
nav:
  - Home: index.md
  - Scripts: scripts.md
  - Data: data.md
  - Output: output.md
